stages:
  load_dataset:
    cmd: python ./src/data/load_dataset.py
    deps:
    - ./src/data/load_dataset.py
    # here this params: section is optional, am writing here for better understanding the complete flow 
    params:
    - data_source.drive
    - load_dataset.raw_data
    - load_dataset.file_name
    outs:
    # way to read parameters from params.yaml
    - .${load_dataset.raw_data}/${load_dataset.file_name}.csv     # dump raw data at some loc

  make_dataset:
    cmd: python ./src/data/make_dataset.py
    deps:
    - ./src/data/make_dataset.py
    - .${load_dataset.raw_data}/${load_dataset.file_name}.csv     # depend on raw data dumped in previous stage
    params:
    - make_dataset.test_split
    - make_dataset.random_state
    - make_dataset.processed_data
    - load_dataset.raw_data
    - load_dataset.file_name
    outs:
    - .${make_dataset.processed_data}/train.csv
    - .${make_dataset.processed_data}/test.csv

  train_model:
    cmd: python ./src/models/train_model.py
    deps:
    - .${make_dataset.processed_data}/train.csv     # depend on train.csv &
    # - .${make_dataset.processed_data}/test.csv      # test.csv generated by previous stage
    - ./src/models/train_model.py
    params:
    - train_model.seed
    - train_model.n_estimators
    - train_model.max_depth
    - train_model.model_loc
    - make_dataset.processed_data
    - base.target_col
    outs:
    - .${train_model.model_loc}/model.joblib

  predict_model:
    cmd: python ./src/models/predict_model.py
    deps:
    - ./src/models/predict_model.py
    # my thought is, if train.csv changes then we'll run train_model bt if test.csv changes we'll do prediction
    - .${make_dataset.processed_data}/test.csv
    - .${train_model.model_loc}/model.joblib     # depend on model.joblib generated by previous stage
    params:
    - train_model.model_loc
    - make_dataset.processed_data
    - base.target_col

# try to manually create dir reports and 
# dump this data manually in json files
# ref: day3 sunny 
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
# use plot = False in log_metric(). Useful in case of iteration
plots:
- dvclive/plots/metrics:
    x: step
