base:
  project: creditcard-project
  target_col: Class

data_source:
  drive: https://drive.google.com/file/d/1CW_oiaBAKnDsH45iLUn6J5APUR0-7EqN/view?usp=drive_link

load_dataset:
  raw_data: /data/raw
  file_name: creditcard

make_dataset:
  test_split: 0.3
  random_state: 42
  processed_data: /data/processed

train_model:
  seed: 42
  n_estimators: 10
  max_depth: 7
  model_loc: /models